# Generated by Django 3.2 on 2021-04-21 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booklet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank='True', max_length=255, null='True')),
                ('content', models.TextField(max_length=2048)),
            ],
        ),
    ]
