# Generated by Django 3.2 on 2021-04-22 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booklets', '0002_auto_20210422_1134'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_summary', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='booklet',
            name='note_summary',
            field=models.ForeignKey(blank='True', null='True', on_delete=django.db.models.deletion.CASCADE, to='booklets.note'),
            preserve_default='True',
        ),
    ]
